### ISSUE TITLE
P100 Plug 1.20.0 HW does not work with 2022.7.x 'Auth fail'

### ISSUE THREAD

**Issue by neildsb** [petretiandrea/home-assistant-tapo-p100#209]
Plug P100 work with 2022.6.7 & v1.2.12, 
but not 2022.7.x & v1.2.12

![image](https://user-images.githubusercontent.com/91122872/178302556-05855c73-cdde-4c7b-b3e0-cc0d9a128ffd.png)

'Auth fails' when trying to add a new device in the UI (not via YAML), - password 8 characters all lowercase alpha numeric

![image](https://user-images.githubusercontent.com/91122872/178304083-6235cd46-dc9c-43cb-b3b9-4027d49963f4.png)

**Comment by petretiandrea** [comment]
> Plug P100 work with 2022.6.7 & v1.2.12, but not 2022.7.x & v1.2.12
> 
> ![image](https://user-images.githubusercontent.com/91122872/178302556-05855c73-cdde-4c7b-b3e0-cc0d9a128ffd.png)
> 
> 'Auth fails' when trying to add a new device, - password 8 characters al lowercase alpha numeric



> Plug P100 work with 2022.6.7 & v1.2.12, but not 2022.7.x & v1.2.12
> 
> ![image](https://user-images.githubusercontent.com/91122872/178302556-05855c73-cdde-4c7b-b3e0-cc0d9a128ffd.png)
> 
> 'Auth fails' when trying to add a new device, - password 8 characters al lowercase alpha numeric

Please be more detailed, as I say, report a screen of tapo app where there is hardware and firmware version and report the logs of home assistant when you receive the error. If you are configuring it via configuration.yml report the configuration too

**Comment by TEMPLATER1** [comment]
I tried to remove the tapo integration from hacs completely and reinstall it, but it had no effect. The logs still show the same error as I showed above, and when adding a device via UI, the error: "Invalid authentication".

**Comment by Fernien** [comment]
does your email contain capital letters?

**Comment by Aljosha89** [comment]
Me too with 1.20 hardware and firmware 1.4.10. I do not have capital letters in mail or password.
Before update everything was working, I tried several time to change password, remove plug and add it back.

Every time I receive error Invalid authentication.

**Comment by petretiandrea** [comment]
I think that invalid auth is a problem related to an inconsistency of tapo device. So changing password or email triggers a sort of re-sync and re-establish the consistency (I hope)

**Comment by petretiandrea** [comment]
> I had the same problem with a P100 on HA 2022.7.3, Tapo Controller 1.2.13, Hardware 1.20.0 and Firmware 1.4.10. I fixed it, when i changed the capital letters in the password and removed all symbols from the password, so only letters and numbers.

So with the hardware 1.20.0 is working?

**Comment by neildsb** [comment]
> > I had the same problem with a P100 on HA 2022.7.3, Tapo Controller 1.2.13, Hardware 1.20.0 and Firmware 1.4.10. I fixed it, when i changed the capital letters in the password and removed all symbols from the password, so only letters and numbers.
> 
> So with the hardware 1.20.0 is working?

no, i have changed the Password and Email, no luck

**Comment by TSSimonSemmler** [comment]
> > I had the same problem with a P100 on HA 2022.7.3, Tapo Controller 1.2.13, Hardware 1.20.0 and Firmware 1.4.10. I fixed it, when i changed the capital letters in the password and removed all symbols from the password, so only letters and numbers.
> 
> So with the hardware 1.20.0 is working?

Yeah, after changing the password it worked. This is my P100
![DEDD1662-81C3-4F18-BDE2-490FAAD0EB99](https://user-images.githubusercontent.com/85613967/178355764-1063735d-bf7e-4576-91b6-c40c470e6444.jpeg)

For the first connection I enabled internet for the switch, after this, I blocked it again in my router. Don‘t know if this is relevant

**Comment by petretiandrea** [comment]
> > > I had the same problem with a P100 on HA 2022.7.3, Tapo Controller 1.2.13, Hardware 1.20.0 and Firmware 1.4.10. I fixed it, when i changed the capital letters in the password and removed all symbols from the password, so only letters and numbers.
> > 
> > 
> > So with the hardware 1.20.0 is working?
> 
> no, i have changed the Password and Email, no luck

I asked @TwoPlayer. 

> > > I had the same problem with a P100 on HA 2022.7.3, Tapo Controller 1.2.13, Hardware 1.20.0 and Firmware 1.4.10. I fixed it, when i changed the capital letters in the password and removed all symbols from the password, so only letters and numbers.
> > 
> > 
> > So with the hardware 1.20.0 is working?
> 
> Yeah, after changing the password it worked. This is my P100 ![DEDD1662-81C3-4F18-BDE2-490FAAD0EB99](https://user-images.githubusercontent.com/85613967/178355764-1063735d-bf7e-4576-91b6-c40c470e6444.jpeg)
> 
> For the first connection I enabled internet for the switch, after this, I blocked it again in my router. Don‘t know if this is relevant

This confirm that is not a problem related to library itself (I think) which version of python are you using?

**Comment by petretiandrea** [comment]
> > > I had the same problem with a P100 on HA 2022.7.3, Tapo Controller 1.2.13, Hardware 1.20.0 and Firmware 1.4.10. I fixed it, when i changed the capital letters in the password and removed all symbols from the password, so only letters and numbers.
> > 
> > 
> > So with the hardware 1.20.0 is working?
> 
> no, i have changed the Password and Email, no luck

Can you run this?
`python3 -c "import packaging.tags; print(list(packaging.tags.sys_tags()))"`

if `packaging` not found, install it with `pip install packaging`

**Comment by petretiandrea** [comment]
Ok guys, Internet must be enabled even the integration use it through LAN. There is synchronization mechanism between tapo cloud and tapo device (like authentication info)

**Comment by TwoPlayer** [comment]
> > > > I had the same problem with a P100 on HA 2022.7.3, Tapo Controller 1.2.13, Hardware 1.20.0 and Firmware 1.4.10. I fixed it, when i changed the capital letters in the password and removed all symbols from the password, so only letters and numbers.
> > > 
> > > 
> > > So with the hardware 1.20.0 is working?
> > 
> > 
> > no, i have changed the Password and Email, no luck
> 
> I asked @TwoPlayer.
> 
> > > > I had the same problem with a P100 on HA 2022.7.3, Tapo Controller 1.2.13, Hardware 1.20.0 and Firmware 1.4.10. I fixed it, when i changed the capital letters in the password and removed all symbols from the password, so only letters and numbers.
> > > 
> > > 
> > > So with the hardware 1.20.0 is working?
> > 
> > 
> > Yeah, after changing the password it worked. This is my P100 ![DEDD1662-81C3-4F18-BDE2-490FAAD0EB99](https://user-images.githubusercontent.com/85613967/178355764-1063735d-bf7e-4576-91b6-c40c470e6444.jpeg)
> > For the first connection I enabled internet for the switch, after this, I blocked it again in my router. Don‘t know if this is relevant
> 
> This confirm that is not a problem related to library itself (I think) which version of python are you using?

Sorry, posted the answer with the wrong accout and deleted it, so it don't give confusion 😅
I run my HomeAssistant with Hass.io and the Phyton Version is 3.10.5

**Comment by TwoPlayer** [comment]
> 

For thew whole time or only for the initial setup with the integration?

**Comment by SignalStealer** [comment]
I had the same issue after upgrading to HA 2022.7.0. The plug model is the same, P100, same HW version and same firmware as in the image attached by @TEMPLATER1.

The bulb was added to HA before upgrading to 2022.7.0, only the upgrade broke the connection.

After I changed my TP-Link Cloud password and removed then re-added the device, was I able to make it work again. I used a password with no uppercare characters, just in case (no pun intended, but internally appreciated).

**Comment by lanerobertlane** [comment]
Accidently updated firmware on plugs to 1.20.0, and all of them are now inaccessible in home assistant. I tried removing and readding a plug in HA (i don't have any caps in email or password), and am getting an auth fail. Plugs are not barred from the internet, work fine in the tapo app etc.

**Comment by neildsb** [comment]
ok i tried this morning- still not working :-(
unblocked p100 from internet
checked remote access from internet - ok
upgraded 4.7.3
restart
 invalid config
 The following integrations and platforms could not be set up:
 tapo (Show logs)
 Please check your config and logs.
update to 1.2.13
restart
not working - Retrying setup: None
delete from HA and APP, then re-add
still invalid auth in UI

**Comment by neildsb** [comment]
> Accidently updated firmware on plugs to 1.20.0, and all of them are now inaccessible in home assistant. I tried removing and readding a plug in HA (i don't have any caps in email or password), and am getting an auth fail. Plugs are not barred from the internet, work fine in the tapo app etc.

i did not update the FW, i have a few problems with TP-Link and their KASA plugs, what FW did you upgrade too? do you still have the problem with 2022.6.7?

**Comment by lanerobertlane** [comment]
> > Accidently updated firmware on plugs to 1.20.0, and all of them are now inaccessible in home assistant. I tried removing and readding a plug in HA (i don't have any caps in email or password), and am getting an auth fail. Plugs are not barred from the internet, work fine in the tapo app etc.
> 
> i did not update the FW, i have a few problems with TP-Link and their KASA plugs, what FW did you upgrade too? do you still have the problem with 2022.6.7?

Plug FW 1.4.10 Build 20211104 rel. 35882 
HW 1.20.0 
HA 2022.6.7 
Integration 1.2.13

**Comment by lanerobertlane** [comment]
Looking around other Repos for Tapo stuff, looking for other issues with auth issues on firmware update, and found this. Not sure if relevant. 

https://github.com/fishbigger/TapoP100/issues/69

**Comment by neildsb** [comment]
> > > Accidently updated firmware on plugs to 1.20.0, and all of them are now inaccessible in home assistant. I tried removing and readding a plug in HA (i don't have any caps in email or password), and am getting an auth fail. Plugs are not barred from the internet, work fine in the tapo app etc.
> > 
> > 
> > i did not update the FW, i have a few problems with TP-Link and their KASA plugs, what FW did you upgrade too? do you still have the problem with 2022.6.7?
> 
> Plug FW 1.4.10 Build 20211104 rel. 35882 Plug HW 1.20.0 HA 2022.6.7 Integration 1.2.13

rollback the HACS integration to 1.2.12, its ok and works with me, hopefully we can get a fix for our 1.20.0 HW?

**Comment by petretiandrea** [comment]
A new version of integration released, please try it

**Comment by donoghdb** [comment]
v1.2.14 works for me. Thank you

**Comment by SkoobyDu** [comment]
Hi, all of my p100 plugs are still showing as unavailable after v1.2.14.
![Screenshot_20220712-203418_Home Assistant](https://user-images.githubusercontent.com/43369591/178579156-7242dabb-8bec-4e4e-8e84-4acbab9c8a28.jpg)

**Comment by mcgarley** [comment]
I've just installed v1.2.14 in HA 2022.7.3 and I can add the L530 bulb but I only get the entities for overheating and signal strength. I can't actually do anything with the bulb. I've tried deleting the integration and readding a couple of times and same issue. Any ideas?

**Comment by neildsb** [comment]
> A new version of integration released, please try it (v1.2.14)

your a rock star!

All working, also P100's still blocked from the internet. i did not even have to remove the devices from HA, i upgraded the integeration from 1.2.12 to 1.214 and then 2022.7.3 reboot and we are good to go.

Grazie mille

**Comment by lanerobertlane** [comment]
> A new version of integration released, please try it (v1.2.14)

Fixed my issue. Thanks.

**Comment by samwise22** [comment]
I still have the authentication issue adding via the UI but the Yaml method is working again now following update to v.1.2.14. Thank you for your hard work @petretiandrea

**Comment by petebiggs** [comment]
> A new version of integration released, please try it (v1.2.14)

Fixed my issues, all three plugs working perfectly (and no need to use the yaml method for me).

Grazie di tutto @petretiandrea
