### ISSUE TITLE
Tapo P100 Says Retrying setup: Error communication with API: Cannot connect to host

### ISSUE THREAD

**Issue by Waldoocs** [petretiandrea/home-assistant-tapo-p100#344]
P100 Plug Says: Error communication with API: Cannot connect to host when my router has been turned off and on again. Even though it is set to a reserved IP. It fixes its self after a day or two but any way to fix this so it doesn't happen? 
![image](https://user-images.githubusercontent.com/119974619/212970434-0458f13d-a322-43f7-9274-762c932644aa.png)

**Comment by petretiandrea** [comment]
Probably the router changes your tapo device ip. Check It, and setup It again. I'm working on a feature that allow to change ip address without configure device again

**Comment by petretiandrea** [comment]
Probably the router changes your tapo device ip. Check It, and setup It again. I'm working on a feature that allow to change ip address without configure device again

**Comment by Waldoocs** [comment]
> Probably the router changes your tapo device ip. Check It, and setup It again. I'm working on a feature that allow to change ip address without configure device again

I have set it to reserved ip, so it can't change. It's still the same ip as before.

**Comment by Waldoocs** [comment]
I meant i had already changed it reserved ip to before. And it didn't fix my problem.

**Comment by Zill11** [comment]
I'm getting this same issue with my P100 plugs. Other tapo lights work well but the P100's get this error. They have static IP's assigned that have not changed and correspond the IP on the error. They work well through tapo app. Error from log

Logger: custom_components.tapo.common_setup
Source: custom_components/tapo/common_setup.py:46
Integration: Tapo Controller (documentation, issues)
First occurred: 01:48:16 (39 occurrences)
Last logged: 01:58:51

Failed to setup Error communication with API: Cannot connect to host 192.168.0.159:80 ssl:default [Connect call failed ('192.168.0.159', 80)]
Failed to setup Unexpected exception:

**Comment by petretiandrea** [comment]
v1.5.1 should fix the issue. Anyway, try to remove and re-add devic e

**Comment by Waldoocs** [comment]
> v1.5.1 should fix the issue. Anyway, try to remove and re-add devic e

I updated, removed an re-added the device, still set to static ip. But it still shows same error when router is turned off and on.

**Comment by FermionAlpha** [comment]
I'm also seeing the exact same issue, but on multiple plugs.

They're all on static IPs, I've restarted all of the plugs and the router and I'm using v1.5.1.

**Comment by Veletax** [comment]
Same issue..

**Comment by smarthomegeorge** [comment]
same here

**Comment by mrjrozycki** [comment]
same for me

**Comment by Javirln** [comment]
Any hint on this?

**Comment by Namirred** [comment]
For anyone with this problem, I solved it by rebooting the router, turning off wifi, and turning it back on. I have tried this several times with a 100% success rate.  


Remember to use a device with an ethernet cable.
