### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by mfabiani53** [petretiandrea/home-assistant-tapo-p100#345]
## Version of the integration
I am running always the latest release of the integration
## Configuration
I have two p100 tapo plugs and one tapo strip updated to the latest firmware
## Describe the bug
Everytime i reboot my home assistant i get the same error about tapo controller.
## Debug log
```
2023-01-17 16:15:43.571 ERROR (MainThread) [custom_components.tapo.common_setup] Failed to setup Unexpected exception: 
2023-01-17 16:15:43.579 ERROR (MainThread) [custom_components.tapo.common_setup] Failed to setup Unexpected exception: 
2023-01-17 16:15:43.582 ERROR (MainThread) [custom_components.tapo.common_setup] Failed to setup Unexpected exception: 
2023-01-17 16:17:01.852 ERROR (MainThread) [custom_components.tapo.common_setup] Failed to setup Unexpected exception: 
2023-01-17 16:17:01.861 ERROR (MainThread) [custom_components.tapo.common_setup] Failed to setup Unexpected exception: 
2023-01-17 16:17:01.866 ERROR (MainThread) [custom_components.tapo.common_setup] Failed to setup Unexpected exception: 
```

**Comment by Kaot93** [comment]
Same here unfortunately:

> Logger: homeassistant.setup
> Source: setup.py:202
> First occurred: 17:58:00 (1 occurrences)
> Last logged: 17:58:00
> 
> Setup failed for custom integration tapo: Requirements for tapo not found: ['plugp100==2.4.1'].

**Comment by petretiandrea** [comment]
v1.5.1 should fix this

**Comment by mfabiani53** [comment]
Sorry but the problem is still there... always the same errors..

**Comment by petretiandrea** [comment]
Version 1.6.1 should fix this issue or log more detailed error
