### ISSUE TITLE
Light entity is no longer provided by the tapo integration

### ISSUE THREAD

**Issue by naamah75** [petretiandrea/home-assistant-tapo-p100#825]
## Home Assistant

Core 2025.1.0
Supervisor 2024.12.3
Operating System 14.1
Frontend 20250103.0

## Version of the integration

tapo 3.1.2

## Configuration

L510
da TP-Link
Firmware: 1.1.9
Hardware: 3.0

## Describe the bug

The tapo component is loaded and some integration entries are available (eg. overheat and signal level), but the main entry for the light component is missing.

![image](https://github.com/user-attachments/assets/cd031a13-b2a9-4fd4-a623-f62ddc1643a8)
![image](https://github.com/user-attachments/assets/ca1885ca-3d5c-4e2b-a3df-9c8f2a89994c)

## Debug log

```text

Questo errore ha avuto origine da un'integrazione personalizzata.

Registratore: custom_components.tapo.coordinators
Fonte: helpers/update_coordinator.py:411
Integrazione: TP-Link Tapo (documentazione, problemi)
Prima occorrenza: 08:49:43 (14 occorrenze)
Ultimo accesso: 09:53:41

Error fetching tapo data: Unexpected exception:

```

**Comment by viba1** [comment]
Hi,
Same problem here, since migrating to 2025.1.0.

Some logs:

ERROR (MainThread) [custom_components.tapo.coordinators] Error fetching tapo data: Unexpected exception: [homeassistant.components.light] Error adding entity None for domain light with platform tapo

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 825, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1116, in capability_attributes
    if LightEntityFeature.EFFECT in supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable

**Comment by PlanetCitizen1829381** [comment]
Device info
L535
by TP-Link
Firmware: 1.1.5
Hardware: 3.0

Same Issue for Tapo Smart Bulb L535.
Only occurred after updating HA to 2025.1.
Have restored HA to 2024.12.5 and devices are available again.
HA Core Update 2025.1 seems to break it.

**Comment by samuelepozzebon** [comment]
Same issue with a L630 (firmware 1.1.2).

HA version 2025.1.0

**Comment by TopoAS** [comment]
Same issue with a L530
HA version 2025.1.0

**Comment by indomitorum** [comment]
Exactly the same here. Light entity does not exist all of a sudden. 2025.1 has broken the custom tapo integration for lights 

L530

**Comment by mcderd-coder** [comment]
Same for me today, HA 2025.1.0

L630 bulb (firmware 1.1.2) has become unavailable, my Tapo plugs are still working

**Comment by iDrunK65** [comment]
Same on this with HA 2025.1.0

L530
by TP-Link

Firmware: 1.1.9
Hardware: 3.0

**Comment by Clickfr** [comment]
Same here with two L530 but no issue so far with my L900.

No worry with the plugs.

**Comment by aidanharris** [comment]
I don't think we need all of the "Me too" comments, unless you have something new to add. Please subscribe to the issue instead.

The Tapo integration has had this deprecation WARNING for ages now. I'm guessing this is the culprit?

```
WARNING (MainThread) [homeassistant.components.light] Entity None (<class 'custom_components.tapo.light.TapoLightEntity'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color modes, please create a bug report at https://github.com/petretiandrea/home-assistant-tapo-p100/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
```

**Comment by Clickfr** [comment]
Hummm.... Surprisingly, same issue with my Govee H7020 it stopped working exactly at the same time as the Tapo L530: 23:24:43 on Jan 3rd.

And now both return the same error at statup:

TAPO:

Logger: homeassistant.components.light
Source: helpers/entity_platform.py:825
integration: Light (documentation, issues)
First occurred: 19:32:22 (2 occurrences)
Last logged: 19:32:22

Error adding entity None for domain light with platform tapo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 825, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1116, in capability_attributes
    if LightEntityFeature.EFFECT in supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable



GOVEE:

Logger: homeassistant.components.light
Source: helpers/entity_platform.py:608
integration: Light (documentation, issues)
First occurred: 19:32:23 (1 occurrences)
Last logged: 19:32:23

Error adding entity None for domain light with platform govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 825, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1116, in capability_attributes
    if LightEntityFeature.EFFECT in supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable

**Comment by Clickfr** [comment]
> I don't think we need all of the "Me too" comments, unless you have something new to add. Please subscribe to the issue instead.
> 
> The Tapo integration has had this deprecation WARNING for ages now. I'm guessing this is the culprit?
> 
> ```
> WARNING (MainThread) [homeassistant.components.light] Entity None (<class 'custom_components.tapo.light.TapoLightEntity'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color modes, please create a bug report at https://github.com/petretiandrea/home-assistant-tapo-p100/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
> ```

Yep, the Govee case would confirm your asusmption.

**Comment by edgicat** [comment]
Can confirm same issue with HA Container 2025.1.0.  Rolling HA back to 2024.12.0 does fix the issue.

FYI The Tapo HAC displays as version 3.1.2 & 3.1.4 in different menus, see images

![IMG_20250104_195626](https://github.com/user-attachments/assets/5026742e-3c42-423f-a7f1-309e9d6f17fd)
![IMG_20250104_195607](https://github.com/user-attachments/assets/e622ad49-5b5b-4b1b-a55b-cdb2ea07cd39)

**Comment by djhworld** [comment]
This seems to fix the issue for me, raised a PR https://github.com/petretiandrea/home-assistant-tapo-p100/pull/826

**Comment by edgicat** [comment]
> This seems to fix the issue for me, my light is working again, raised a PR #826
> 
> <img alt="image" width="354" src="https://private-user-images.githubusercontent.com/529730/400168355-eb5fca2f-82e6-4dd1-8756-431326b9b11d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwMzQwMTksIm5iZiI6MTczNjAzMzcxOSwicGF0aCI6Ii81Mjk3MzAvNDAwMTY4MzU1LWViNWZjYTJmLTgyZTYtNGRkMS04NzU2LTQzMTMyNmI5YjExZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNFQyMzM1MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDlhNDgxNzM3ZWI4Yzc1YzgxYmRjNDFjYTYxNTFmN2JiOGZmMzMyMzZkOWUwZDkwOTZhNjM2OGJiZjUwNzAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6ktqx5Iw_3UBV9wxC8zKwYishG1Ej0-mOJYPQiF5RM0">

Confirmed works for me
![Screenshot_2025-01-04-23-36-43-38_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/ae64312f-4fdc-48e1-a1bd-2ab3db238d4e)
![Screenshot_2025-01-04-23-35-40-55_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/22188e96-f8f6-4f19-821f-17691656fc70)

Interesting light brightness percentage glitch on HA Gui, I take it that's an HA issue

**Comment by boblemus** [comment]
@djhworld Sadly the control is completely disabled and cannot be toggled by me (everything same version as you, except L530 HW is 3.0 and FW is 1.1.9)

**Comment by edgicat** [comment]
> @djhworld Sadly the control is completely disabled and cannot be toggled by me (everything same version as you, except L530 HW is 3.0 and FW is 1.1.9)

Hey boblemus,

Have you updated the python script and restarted HA, as per:
https://github.com/petretiandrea/home-assistant-tapo-p100/pull/826 

If not you will need to wait for HACS component update to come through.

**Comment by boblemus** [comment]
@edgicat  Ahh - I missed the part about modifying the Python script. Apparently that did the trick - thank you!!

**Comment by mcderd-coder** [comment]
Thank you, I made the change, it's now working fine again 👍

**Comment by bobfoyers** [comment]
Same issue with a L630 (firmware 1.1.2).

HA version 2025.1.0

**Comment by Av4K100** [comment]
Have implemented the change mentioned in PR 826 however with this change it seems to be affecting light groups in homeassistant, for example i have three bathroom lights combined into a bathroom lights group and after this change i can no longer group these lights together for them to work (the entity shows as unavailable, have deleted and readded and still the same). Rolling back the update and changes to light.py resolve the issue

**Comment by Av4K100** [comment]
Changing lines 54-56 in light.py to `self._attr_supported_features = (LightEntityFeature.EFFECT)` as mentioned by pgarciafc on PR #826 has fixed the light group and entity issues on L630 bulbs for myself

**Comment by djhworld** [comment]
@Av4K100  I've updated the PR with a similar change - does this fix the group issue?

**Comment by Adagis-MC** [comment]
@djhworld I've retested this on with my P100s in a group. The error still occurs.

**Comment by boblemus** [comment]
I have 2 groups, a generic group with 3 L530 and 1 P110, and a light group
with the same 3 L530.

light.py has been modified as such:
#        self._attr_supported_features = (
#            LightEntityFeature.EFFECT if self._effects else []
#        )
        self._attr_supported_features = (LightEntityFeature.EFFECT) if
self._effects else ()

Prior to commenting the above out and adding the one line the generic group
worked and the light group didn't (unavailable). No change to this
behaviour can be observed after modifying as above and restarting HA.

**Comment by Av4K100** [comment]
@boblemus removing the `if self._effects else ()` at the end of the code should allow the groups to work however as noted in PR #826 by pgarciafc there could be other issues, might be worth giving a try for yourself to see if that sorts the problem for you until there is a full fix implemented

**Comment by boblemus** [comment]
> @boblemus removing the `if self._effects else ()` at the end of the code should allow the groups to work however as noted in PR #826 by pgarciafc there could be other issues, might be worth giving a try for yourself to see if that sorts the problem for you until there is a full fix implemented

Can confirm. Removing "if self._effects else ()" made both generic and light groups work.

**Comment by djhworld** [comment]
Looks like we have a fix in https://github.com/petretiandrea/home-assistant-tapo-p100/pull/826 to return `LightEntityFeature(0)` instead of `0` which seems promising for both the ungrouped and grouped cases

**Comment by djhworld** [comment]
For reference looks like this issue was caused by this https://github.com/home-assistant/core/pull/132371

**Comment by carvan** [comment]
Just applied this fix:
![image](https://github.com/user-attachments/assets/efd9be28-e8ab-4983-b6e0-7fc97261491b)
But the light entity looks to be unavailable still:

![image](https://github.com/user-attachments/assets/f71bd0aa-cfa9-4cf4-a217-aab9cbd42cb5)

Did I make something wrong?

**Comment by Adagis-MC** [comment]
@carvan. Yes.

The 
else set()
should be 
else LightEntityFeature(0)

as shown in theatest commit.

**Comment by carvan** [comment]
> @carvan. Yes.
> 
> 
> 
> The 
> 
> else set()
> 
> should be 
> 
> else LightEntityFeature(0)
> 
> 
> 
> as shown in theatest commit. 

Oh ok that makes sense then. I honestly just copied it from the other post without even reading it assuming it was correct. Thank you

**Comment by dimitrispili** [comment]
Does anyone knows if Home Assistant Core 2025.1.2 version, solve the problem or we have to do it manually again?

**Comment by Lockie85** [comment]
I'm on latest everything and all seems good for me now.
